"use client";

import React from "react";

/**
 * WarningModal Component
 * Shows a disclaimer about AI hallucinations and accuracy.
 */
export default function WarningModal({ onAccept, onClose }) {
  const handleAccept = () => {
    localStorage.setItem("aiWarningAccepted", "true");
    onAccept();
  };

  return (
    <div className="fixed inset-0 z-[2000] flex items-center justify-center bg-slate-900/80 p-4 backdrop-blur-sm">
      <div className="w-full max-w-md overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl">
        <div className="bg-amber-50 p-6 text-amber-800">
          <div className="flex items-center gap-3">
            <span className="flex h-10 w-10 items-center justify-center rounded-full bg-amber-100 text-xl">
              ⚠️
            </span>
            <h2 className="text-xl font-black tracking-tight">Legal Disclaimer</h2>
          </div>
          <p className="mt-4 text-sm font-medium leading-relaxed">
            Everything in this AI Moot Court is generated by Artificial Intelligence. 
            Information may be <strong>inaccurate, hallucinated, or contain fake citations</strong>.
          </p>
        </div>

        <div className="p-8">
          <p className="text-sm font-medium text-slate-600 leading-relaxed">
            This tool is for educational simulation only. You must verify all legal 
            principles, sections, and case laws using official sources like:
          </p>
          <ul className="mt-4 space-y-2 text-xs font-bold text-indigo-600">
            <li>• Indian Kanoon / SCC Online</li>
            <li>• LexisNexis / Westlaw</li>
            <li>• Official Court Gazettes</li>
          </ul>

          <div className="mt-8 flex flex-col gap-3">
            <button
              onClick={handleAccept}
              className="w-full rounded-2xl bg-slate-950 py-4 text-sm font-black uppercase tracking-widest text-white transition-all hover:bg-indigo-600 active:scale-95"
            >
              I Understand – Proceed
            </button>
            <button
              onClick={onClose}
              className="w-full rounded-2xl border border-slate-200 py-4 text-sm font-black uppercase tracking-widest text-slate-500 transition-all hover:bg-slate-50 active:scale-95"
            >
              Decline & Go Back
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
